### ISSUE TITLE
Constant High Mode doesn't work intermittently on video apps(S23 Ultra)

### ISSUE THREAD

**Issue by Stix3n** [tribalfs/GalaxyMaxHzPub#186] opened 2024-05-01 04:18 UTC
Hi,

I have a very bothering issue with GalaxyMaxHz on my SAMSUNG GALAXY S23 ULTRA (OneUi 6.0).

**When I settle a fresh rate (Constant High Mode) on the app (for example 96 Hz), the fresh rate is not constant.**

**Indeed, when I look a video on Youtube, on MX PLAYER PRO, VLC, etc, the fresh rate go down to 60 Hz or worst, to 24 Hz...**
Normally, it should stay at 96 Hz...

When I installed the GalaxyMaxHz in December 2023, I had this issue for few hours and then after several changes on the app (Constant High 60 Hz, Constant High 120 Hz, etc), the issue has been fixed by itself.
During 2 or 3 weeks, no issue (96 Hz everytime, also when I look a video).
And then, without any explanation, the issue comes back in January, February, etc...

If I use Constant High 60 Hz, I have no issue.

But if I use Constant High 96 Hz or Constant High 120 Hz, the issue appears on videos playback...
The fresh rate go down to 60 Hz, 30 Hz and also 24 Hz....

Sometimes, the issue also appears on web pages reading.

I am not satisfied. 
I want to use Constant High 96 Hz everytime, also when I look a video...

Because, when the fresh rate drops, I got some lags on videos playback.

I had the issue on the previous versions and on the last version on GalaxyMaxHz.

Could you help me?

Thank you in advance.

**Comment by tribalfs** [comment] 2024-05-03 14:50
Do you have the latest version (8.1.75) installed?

**Comment by Stix3n** [comment] 2024-05-03 16:08
Hi @tribalfs 

Yes, I have the latest version installed.

**Comment by tribalfs** [comment] 2024-05-03 22:49
I can't reproduce the issue on my devices.
Can you redownload and reinstall it?

**Comment by Stix3n** [comment] 2024-05-03 23:11
Hi @tribalfs 

I have deleted all data of the GalaxyMaxHz app, uninstalled it and then reinstalled it.
I have also granted, again, "WRITE_SECURE_SETTINGS" via ADB.
Unfortuantely, this very annoying issue persists...

Do you have the same smartphone as me (SAMSUNG GALAXY S23 ULTRA on Android 14 / One Ui 6.0)?

**Comment by tribalfs** [comment] 2024-05-04 01:44
Did you re-download it?

I don't have exact device but I tested both on S22Ultra and ZFold5 both with same refresh rate profile with S23Ultra

**Comment by Stix3n** [comment] 2024-05-04 02:07
@tribalfs 

I've just re-downloaded the last apk file.
I've uninstalled and reinstalled it.
Unfortunately, I have always the same issue...

**Comment by tribalfs** [comment] 2024-05-04 08:01
Tested on 24fps, 30fps and 60fps videos.
Though, there are still a few apps that don't respect the constant high settings but didn't notice it in youtube and mx.

https://drive.google.com/file/d/1Kyetm8RN_BTma0MDvkDbeMKrb-pEizvk/view?usp=sharing

**Comment by Stix3n** [comment] 2024-05-04 11:19
Hi @tribalfs 

I don't have the same menu as you on the GalaxyMaxHz app.

In refresg rate mods, I don't have:

"Keep selected mod on PSM"
"Per-app settings"

Please look at the first picture below (screen n°01)

![SCREEN_01](https://github.com/tribalfs/GalaxyMaxHzPub/assets/168615482/a4c658c6-9e9e-4995-b6bd-8913c85ad512)


On "Default refresh rates" menu, I don't have the refresh rate for "Normal power mode", "Power saving mode" and "Low battery".

Please look at the second picture below (screen n°02)

![SCREEN_02](https://github.com/tribalfs/GalaxyMaxHzPub/assets/168615482/758c690d-7751-4ef9-b2cc-3bb60cc8f9c4)


Why?
Is it normal?

**Comment by tribalfs** [comment] 2024-05-04 11:29
They are [premium features](https://github.com/tribalfs/GalaxyMaxHzPub)

**Comment by Stix3n** [comment] 2024-05-04 11:39
@tribalfs 

1) Premium features has nothing to do with my issue?
(Note: I can't access to your second Google Drive link. I sent you an authorization access).

2) For now, I am at 96 Hz on Youtube (all video) and MX Player Pro (all videos).
But I did nothing for that.
It's very strange!

But, like I told you on my first post, it's temporary.

Every time, all work fine during 2 or 3 weeks, and then, without any explanation, the refresh rate goes down to 60 Hz, 48 Hz and 24 hz on Youtube and MX Player Pro...

It's illogical...

Where does this issue come from?

(Please let this post opened here, in "issue" section)

**Comment by tribalfs** [comment] 2024-05-04 12:09
Check if Is it happening when you're phone is in power saving mode. If it is, it is an expected behavior, unless you perform the EXTRA STEPS provided in the app description.

**Comment by Stix3n** [comment] 2024-05-04 12:31
@tribalfs 

1- You haven't answered to my question about your second Google Drive link.

What was it?

2- Power saving mode is always disabled on my phone.
I don't use it.

**Comment by tribalfs** [comment] 2024-05-05 02:02
1 - link already public.

2 - check if adaptive power saving mode might be turned on when battery is low.

We should be able to reproduce it so we can pinpoint the exact cause and fix it if necessary..

**Comment by Stix3n** [comment] 2024-05-05 10:18
Hi @tribalfs 

Adaptative power saving mode is disabled on my S23 ULTRA, for several months (since December 2023).

**Comment by tribalfs** [comment] 2024-05-06 01:23
It's strange. Never experienced that on video apps. 

Actually, the behavior for (constant) high mode is a oneui implementation, not by the app. The app just sets it to that hidden settings.

**Comment by tribalfs** [comment] 2024-05-06 01:49
correct

**Comment by tribalfs** [comment] 2024-05-08 04:11
Only able to reproduce it when on power saving mode (and extra steps provided in the app is not performed).
This behavior is also controlled by oneui, not by the app.
Closing this for now.
You may still message here.

**Closed by tribalfs** 2024-05-08 04:11 UTC

**Comment by Stix3n** [comment] 2024-05-08 10:44
Hi @tribalfs 

Why did you close my post/issue?

I asked you to let it opened...

My issue is NOT fixed.
And moreover, like I told you before,  power saving mode is always disabled on my GALAXY S23 ULTRA.

Adaptative power saving mode is also disabled on my phone.

So, the issue is elsewhere.

**Comment by tribalfs** [comment] 2024-05-08 12:09
As mentioned, it can't be fixed by the app.

**Comment by Stix3n** [comment] 2024-05-08 12:15
So, I have to put up with this issue forever...
I am unsatisfied..

**Comment by tribalfs** [comment] 2024-05-08 12:20
I already mentioned it's a oneui system implementation and beyond control of the app.
